version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Kolkata"
    labels:
      - ":robot: bot"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Kolkata"
    labels:
      - ":robot: bot"
