name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup upx
        shell: bash
        run: |
          set -x
          git fetch --force --tags
          mkdir -p /tmp/upx
          cd /tmp/upx
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz -O - | tar -C . -xJf -
          cp $(find . -name 'upx' -type f) /usr/local/bin/upx

      - name: Setup go
        uses: actions/setup-go@v3
        with: { go-version: 1.18 }

      - name: Cache go mods
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          versison: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  instl-test:
    needs: [goreleaser]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test in ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          set +e -x
          curl -fsSL instl.sh/daftcreations/gcps/linux | bash
          export PATH=$PATH:$HOME/.local/bin
          zipper -version
          exit $?

      - name: test in macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          set +e -x
          curl -fsSL instl.sh/daftcreations/gcps/macos | bash
          export PATH=$PATH:$HOME/.local/bin
          zipper -version
          exit $?
