name: lint
on:
  push:
    paths:
      - "**.go"
      - "go.*"
      - ".github/workflows/lint.yaml"
      - "!**.md"
    tags-ignore:
      - "*"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with: { go-version: 1.18 }
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
