name: test

on:
  push:
    paths:
      - "**/**.go"
      - "**/go.**"
      - ".github/workflows/test.yaml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.17.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
            ~/.cache/go-build
            ~/go/pkg/mod
          key: gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            gomod-

      - run: |
          go test -race ./...
