name: test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        if: matrix.os != 'ubuntu-latest'
        with:
          go-version: 1.17.x

      - uses: actions/cache@v2
        if: matrix.os != 'ubuntu-latest'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go test
        if: matrix.os != 'ubuntu-latest'
        run: |
          go test ./...
          go test -race ./...

      - name: Setup QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        if: matrix.os == 'ubuntu-latest'
        uses: docker/bake-action@master
        with:
          targets: test
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
