name: test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - uses: bazelbuild/setup-bazelisk@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum','**/BUILD.bazel','**/WORKSPACE' ) }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        env:
          os: ${{ matrix.os }}
        shell: bash
        run: |
          if [[ $os =~ "windows*" ]]; then TARGET_FRONEND='///'; fi
          bazelisk test //...

      - name: Build (test)
        env:
          os: ${{ matrix.os }}
        shell: bash
        run: |
          if [[ $os =~ "windows*" ]]; then TARGET_FRONEND='///'; fi
          bazelisk build ${TARGET_FRONEND:-'//'}...
