name: test

on:
  push:
    paths:
      - "**.go"
      - "go.*"
      - ".github/workflows/test.yaml"
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Cache go mods
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-
      - run: go test -v -race ./...
